import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import Navbar from "../uikits/navbar";
import "./styles/index.scss";
import "./styles/slick.min.css";

import Footer from "@/uikits/footer";

const inter = Work_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
